### Remove:
* Null values, new_line("\n"), hashtags("#*"), emojis, other characters
### Replace:
* ['ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሖ'] with ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']
* ['ኀ', 'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ'] with ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']
* ['ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሦ', 'ሦ', 'ሧ'] with ['ሰ, 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ', 'ሶ', 'ሷ']
* ['ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ'] with ['አ', 'ኡ', 'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ']
* ['ጸ', 'ጹ', 'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ'] with ['ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ']

In [1]:
import sys, os
import pandas as pd
sys.path.append(os.path.abspath(os.path.join('../scripts')))
from util import Util

In [78]:
parsed_dir = "../data/raw/"
cleaned_dir = "../data/parsed/"
file_name = "TIKVAH-data"
util = Util()

Loading  the Raw files

In [3]:
df = pd.read_json(f"{parsed_dir}/{file_name}.json")
df.head()

,name,type,id,messages
0,TIKVAH-ETHIOPIA,public_channel,1130580549,"{'id': 1, 'type': 'service', 'date': '2017-07-..."
1,TIKVAH-ETHIOPIA,public_channel,1130580549,"{'id': 12, 'type': 'message', 'date': '2017-07..."
2,TIKVAH-ETHIOPIA,public_channel,1130580549,"{'id': 14, 'type': 'message', 'date': '2017-07..."
3,TIKVAH-ETHIOPIA,public_channel,1130580549,"{'id': 15, 'type': 'message', 'date': '2017-07..."
4,TIKVAH-ETHIOPIA,public_channel,1130580549,"{'id': 17, 'type': 'message', 'date': '2017-07..."

In [5]:
df = pd.DataFrame(df['messages'])
df_messages = pd.DataFrame(df['messages'].tolist())
df_messages['text'] = df_messages['text'].apply(lambda x: ' '.join([i if isinstance(i, str) else i['text'] for i in x if isinstance(i, str) or ('text' in i and isinstance(i['text'], str))]))
df_messages = df_messages[['id', 'text', 'date']]
df_messages

,id,text,date
0,1,,2017-07-03T21:36:19
1,12,ታሪክ የሌለው ህዝብ ታሪካዊ ስራ ለመስራት አይጓጓም። ነፃነትም የማያውቅ ...,2017-07-27T11:37:49
2,14,ኢትዮጵያ ኣደይ !\n\n @tikvahethiopia,2017-07-27T11:52:34
3,15,አ ደ ራ ል ጄ \n \n ገ ን ዘ ብ ው ር ሴ ን አ ም ጪ ...,2017-07-27T12:13:05
4,17,ኢትዮጵያ ሀገሬ መመኪያ ነሽ ክብሬ !\n\n @tikvahethiopia,2017-07-27T13:15:01
...,...,...,...
64897,84209,#Ethiopia \n\nየጠቅላይ ሚኒስትሩ የብሔራዊ ደህንነት አማካሪ አምባ...,2024-01-12T00:19:12
64898,84214,,2024-01-12T00:54:13
64899,84215,,2024-01-12T00:54:13
64900,84216,,2024-01-12T00:54:13
64901,84217,""" በምጥ የተያዘችን እናት ሊያመጣ ሲሄድ በተተኮሰበት ጥይት ተመቶ ህይወቱ...",2024-01-12T00:54:13

In [36]:
df_filtered = df_messages[(df_messages['id'] >= 60000) & (df_messages['id'] <= 75000)]
df_filtered.head()

,id,text,date
44471,60001,,2021-06-16T15:12:46
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች።\n \nከኢፌዴሪ የውጭ ጉ...,2021-06-16T15:12:46
44473,60003,#Update \n\nእናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪ...,2021-06-16T15:14:54
44474,60004,#ምርጫ2013 \n\nምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድ...,2021-06-16T16:10:44
44475,60005,#UN \n\nትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት...,2021-06-16T16:17:46

Remove null values

In [9]:
data_null_removed = df_filtered.dropna()
data_null_removed.head()

,id,text,date
44471,60001,,2021-06-16T15:12:46
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች።\n \nከኢፌዴሪ የውጭ ጉ...,2021-06-16T15:12:46
44473,60003,#Update \n\nእናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪ...,2021-06-16T15:14:54
44474,60004,#ምርጫ2013 \n\nምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድ...,2021-06-16T16:10:44
44475,60005,#UN \n\nትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት...,2021-06-16T16:17:46

Remove new line

In [49]:
tigvah_data = data_null_removed.replace('\n', ' ', regex=True)
tigvah_data.head()

,id,text,date
44471,60001,,2021-06-16T15:12:46
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46
44473,60003,#Update እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ ...,2021-06-16T15:14:54
44474,60004,#ምርጫ2013 ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ...,2021-06-16T16:10:44
44475,60005,#UN ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የ...,2021-06-16T16:17:46

Extract and remove hasthags

In [50]:
# Extract hashtags
tigvah_data['hashtags'] = tigvah_data['text'].apply(lambda x: util.extract_hashtags(x))
tigvah_data.head()

,id,text,date,hashtags
44471,60001,,2021-06-16T15:12:46,[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[]
44473,60003,#Update እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]"
44474,60004,#ምርጫ2013 ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ...,2021-06-16T16:10:44,[#ምርጫ2013]
44475,60005,#UN ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የ...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]"

In [51]:
# Remove hashtags from text
tigvah_data['text'] = tigvah_data['text'].str.replace(r'\#\w+', '', regex=True)
tigvah_data.head()

,id,text,date,hashtags
44471,60001,,2021-06-16T15:12:46,[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ - 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]"
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013]
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]"

Extract emojies

In [52]:
# Extract emojis using regex
tigvah_data['emojis'] = tigvah_data['text'].apply(util.extract_emojis)
tigvah_data.tail()

,id,text,date,hashtags,emojis
56623,74994,,2022-12-07T09:53:23,[],
56624,74995,,2022-12-07T09:53:23,[],
56625,74996,"በርካታ ወላጆችን ያስጨነቀው የ "" ፍራንስ ሌይ "" የህፃናት ወተት ጉዳይ ...",2022-12-07T09:53:23,[#ኢትዮጵያ],
56626,74999,,2022-12-07T09:54:20,[],
56627,75000,ቄስ በሊና ሳርካ አረፉ። የኢትዮጵያ ወንጌል አማኞች አብያተ ክርስቲያናት...,2022-12-07T09:54:20,[],

In [53]:
tigvah_data['text'] = tigvah_data['text'].apply(util.remove_emojis)
tigvah_data.head()

,id,text,date,hashtags,emojis
44471,60001,,2021-06-16T15:12:46,[],
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳዑዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ - 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",

#### Replace letters:
* ['ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሖ'] with ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']
* ['ኀ', 'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ'] with ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']
* ['ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሦ', 'ሦ', 'ሧ'] with ['ሰ, 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ', 'ሶ', 'ሷ']
* ['ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ'] with ['አ', 'ኡ', 'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ']
* ['ጸ', 'ጹ', 'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ'] with ['ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ']

In [54]:
letters = [
  [['ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሖ'], ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']],
  [['ኀ', 'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ'], ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ']],
  [['ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሦ', 'ሦ', 'ሧ'], ['ሰ', 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ', 'ሶ', 'ሷ']],
  [['ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ'], ['አ', 'ኡ', 'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ']],
  [['ጸ', 'ጹ', 'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ'], ['ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ']]
]
for letter in letters:
  for i in range(len(letter[0])):
    tigvah_data['text'] = tigvah_data['text'].str.replace(letter[0][i], letter[1][i])

In [63]:
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols
44471,60001,,2021-06-16T15:12:46,[],,
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],,
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],,
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,

Extract Symbols

In [64]:
tigvah_data['symbols'] = tigvah_data['text'].apply(util.extract_symbols)
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols
44471,60001,,2021-06-16T15:12:46,[],,
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],,
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],,
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,

In [66]:
tigvah_data['text'] = tigvah_data['text'].apply(util.remove_symbols)
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols
44471,60001,,2021-06-16T15:12:46,[],,
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],,
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],,
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,

Extract Links

In [69]:
tigvah_data['links'] = tigvah_data['text'].apply(util.extract_urls)
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols,links
44471,60001,,2021-06-16T15:12:46,[],,,[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],,,[]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],,,[]
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[]

In [70]:
tigvah_data['links'] = tigvah_data['text'].apply(util.extract_urls)
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols,links
44471,60001,,2021-06-16T15:12:46,[],,,[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ...,2021-06-16T15:12:46,[],,,[]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይ...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወ...,2021-06-16T16:10:44,[#ምርጫ2013],,,[]
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርት...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[]

Extract mentions

In [73]:
tigvah_data['mentions'] = tigvah_data['text'].apply(util.extract_mentions)
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols,links,mentions
44471,60001,,2021-06-16T15:12:46,[],,,[],[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ ሚ...,2021-06-16T15:12:46,[],,,[],[tikvahethiopia]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይዘው በጳው...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[],[tikvahethiopia]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወሰነ።...,2021-06-16T16:10:44,[#ምርጫ2013],,,[],"[nebe, tikvahethioia]"
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርትራ ወ...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[],[tikvahethiopia]

In [75]:
tigvah_data['text'] = tigvah_data['text'].str.replace(util.mention_pattern, '', regex=True).str.strip()
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols,links,mentions
44471,60001,,2021-06-16T15:12:46,[],,,[],[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ ሚ...,2021-06-16T15:12:46,[],,,[],[tikvahethiopia]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይዘው በጳው...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[],[tikvahethiopia]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወሰነ።...,2021-06-16T16:10:44,[#ምርጫ2013],,,[],"[nebe, tikvahethioia]"
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርትራ ወ...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[],[tikvahethiopia]

Remove extra spaces

In [72]:
tigvah_data['text'] = tigvah_data['text'].str.replace('\s+', ' ', regex=True).str.strip()

,id,text,date,hashtags,emojis,symbols,links
44471,60001,,2021-06-16T15:12:46,[],,,[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ ሚ...,2021-06-16T15:12:46,[],,,[]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይዘው በጳው...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወሰነ።...,2021-06-16T16:10:44,[#ምርጫ2013],,,[]
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርትራ ወ...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[]

In [76]:
tigvah_data['text'] = tigvah_data['text'].replace(r'!+', '!', regex=True)
tigvah_data['text'] = tigvah_data['text'].replace(r'\.+', '', regex=True)

In [77]:
tigvah_data.head()

,id,text,date,hashtags,emojis,symbols,links,mentions
44471,60001,,2021-06-16T15:12:46,[],,,[],[]
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ ሚ...,2021-06-16T15:12:46,[],,,[],[tikvahethiopia]
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይዘው በጳው...,2021-06-16T15:14:54,"[#Update, #AGOHELMA]",,,[],[tikvahethiopia]
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወሰነ።...,2021-06-16T16:10:44,[#ምርጫ2013],,,[],"[nebe, tikvahethioia]"
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርትራ ወ...,2021-06-16T16:17:46,"[#UN, #ቢቢሲ]",,,[],[tikvahethiopia]

save cleaned dataframe

In [81]:
tigvah_data = tigvah_data.drop(['hashtags', 'emojis', 'symbols', 'links', 'mentions'], axis=1)

In [82]:
tigvah_data

,id,text,date
44471,60001,,2021-06-16T15:12:46
44472,60002,ኢትዮጵያ 381 ዜጎቿን ከሳኡዲ አረብያ መለሰች። ከኢፌዴሪ የውጭ ጉዳይ ሚ...,2021-06-16T15:12:46
44473,60003,እናታችን ክብርት ዶ/ር አበበች ጎበና (እዳዬ) በኮቪድ 19 ተይዘው በጳው...,2021-06-16T15:14:54
44474,60004,ምርጫ ቦርድ ለግል እጩ ተወዳዳሪዎች 50 ሺህ ብር ድጋፍ ለማድረግ ወሰነ።...,2021-06-16T16:10:44
44475,60005,ትግራይ ክልል ውስጥ በተካሄደው ጦርነት ውስጥ ተሳታፊ የሆኑት የኤርትራ ወ...,2021-06-16T16:17:46
...,...,...,...
56623,74994,,2022-12-07T09:53:23
56624,74995,,2022-12-07T09:53:23
56625,74996,በርካታ ወላጆችን ያስጨነቀው የ ፍራንስ ሌይ የህፃናት ወተት ጉዳይ ምንድነ...,2022-12-07T09:53:23
56626,74999,,2022-12-07T09:54:20
56627,75000,ቄስ በሊና ሳርካ አረፉ። የኢትዮጵያ ወንጌል አማኞች አብያተ ክርስቲያናት ...,2022-12-07T09:54:20

In [80]:
tigvah_data.to_csv(f"{cleaned_dir}/{file_name}.csv")